- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Add Jenkins key and repo
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
      /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
      https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null
  args:
    executable: /bin/bash

- name: Update again
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add Jenkins to Docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Enable and start Jenkins
  systemd:
    name: jenkins
    enabled: yes
    state: started
